name: Docker Image CI

on:
  push:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: true 
    - name: Install Protoc
      uses: arduino/setup-protoc@v1
    - name: Build protos
      run: make proto
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1      
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CR_PAT }}      
    - name: Build and push Docker images
      uses: docker/build-push-action@v2.2.1
      with:
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/bradley-www:latest
